// <auto-generated />
using System;
using HASOapi2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HASOapi2.Migrations
{
    [DbContext(typeof(HASODBContext))]
    [Migration("20200627193302_HASOapi2.Models.HASODBContext3")]
    partial class HASOapi2ModelsHASODBContext3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HASOapi2.Models.Classe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdProf")
                        .HasColumnType("bigint");

                    b.Property<long>("Members")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classe");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "this is specially made to be able to share with your math teacher",
                            IdProf = 1L,
                            Members = 0L,
                            Name = "MATHEMATICS"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "this is specially made to be able to share with your PHYSICS teacher",
                            IdProf = 1L,
                            Members = 0L,
                            Name = "PHYSICS"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "this is specially made to be able to share with your CHEMISTRY teacher",
                            IdProf = 1L,
                            Members = 0L,
                            Name = "CHEMISTRY"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "this is specially made to be able to share with your FRENSH teacher",
                            IdProf = 2L,
                            Members = 0L,
                            Name = "FRENSH"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "this is specially made to be able to share with your ENGLISH teacher",
                            IdProf = 2L,
                            Members = 0L,
                            Name = "ENGLISH"
                        });
                });

            modelBuilder.Entity("HASOapi2.Models.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contenus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdPublication")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Contenus = "first comment",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdPublication = 1L,
                            IdUser = 1L
                        });
                });

            modelBuilder.Entity("HASOapi2.Models.Publication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contenus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdClasse")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Publication");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Contenus = "this is the first publication.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdClasse = 1L,
                            IdUser = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Contenus = "this is the second publication.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdClasse = 1L,
                            IdUser = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Contenus = "this is the third publication.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdClasse = 1L,
                            IdUser = 2L
                        },
                        new
                        {
                            Id = 4L,
                            Contenus = "this is the fourth publication.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdClasse = 2L,
                            IdUser = 3L
                        },
                        new
                        {
                            Id = 5L,
                            Contenus = "this is the fifth publication.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdClasse = 3L,
                            IdUser = 3L
                        },
                        new
                        {
                            Id = 6L,
                            Contenus = "this is the sixth publication.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdClasse = 4L,
                            IdUser = 3L
                        },
                        new
                        {
                            Id = 7L,
                            Contenus = "this is the seventh publication.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdClasse = 5L,
                            IdUser = 1L
                        },
                        new
                        {
                            Id = 8L,
                            Contenus = "this is the eightth publication.",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdClasse = 5L,
                            IdUser = 4L
                        });
                });

            modelBuilder.Entity("HASOapi2.Models.Uploadedfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdPublication")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint");

                    b.Property<string>("path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uploadedfile");
                });

            modelBuilder.Entity("HASOapi2.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "prof1@bla.com",
                            Login = "prof1",
                            Name = "Professor 1",
                            Password = "123",
                            Phone = "0123456789",
                            Role = "Professor"
                        },
                        new
                        {
                            Id = 2L,
                            Email = "prof2@bla.com",
                            Login = "prof2",
                            Name = "Professor 2",
                            Password = "123",
                            Phone = "0123456789",
                            Role = "Professor"
                        },
                        new
                        {
                            Id = 3L,
                            Email = "stud1@bla.com",
                            Login = "stud1",
                            Name = "Student 1",
                            Password = "123",
                            Phone = "0123456789",
                            Role = "Student"
                        },
                        new
                        {
                            Id = 4L,
                            Email = "stud2@bla.com",
                            Login = "stud2",
                            Name = "Student 2",
                            Password = "123",
                            Phone = "0123456789",
                            Role = "Student"
                        },
                        new
                        {
                            Id = 5L,
                            Email = "stud3@bla.com",
                            Login = "stud3",
                            Name = "Student 3",
                            Password = "123",
                            Phone = "0123456789",
                            Role = "Student"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
